version: '3'
services: 
    dotnet-project:
        build: ./FirstDotNetProject
        restart: 'on-failure'
    node-app:
        build: ./simpleweb
        restart: 'always'
        ports: 
            - "4001:8080"